version: '3.9'
services:
  zurich-open_db:
    image: postgres:16
    container_name: zurich-open_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zurich-open
    ports:
      - "5441:5432"
    volumes:
      - zurich-open_db_data:/var/lib/postgresql/data

  zurich-open_service:
    build:
      context: ../../tenants/zurich-open
    container_name: zurich-open_service
    restart: always
    ports:
      - "4134:4100"
    env_file:
      - ../../tenants/zurich-open/.env

volumes:
  zurich-open_db_data: